SET XACT_ABORT ON;
GO
CREATE TABLE dbo.PatientFile(FileUid UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_PatientFile_FileUid DEFAULT NEWSEQUENTIALID(),PatientUid UNIQUEIDENTIFIER NOT NULL,OriginalFileName NVARCHAR(255) NOT NULL,StorageKey NVARCHAR(500) NOT NULL,ContentType NVARCHAR(200) NOT NULL,FileSizeBytes BIGINT NOT NULL,FileExtension NVARCHAR(20) NULL,Sha256Hash CHAR(64) NULL,Description NVARCHAR(1000) NULL,Category NVARCHAR(100) NULL,Status NVARCHAR(20) NOT NULL CONSTRAINT DF_PatientFile_Status DEFAULT N'Active',UploadedAt DATETIME2(0) NOT NULL CONSTRAINT DF_PatientFile_UploadedAt DEFAULT SYSUTCDATETIME(),UploadedBy BIGINT NOT NULL,UpdatedAt DATETIME2(0) NULL,UpdatedBy BIGINT NULL,RowVersion ROWVERSION NOT NULL,CONSTRAINT PK_PatientFile PRIMARY KEY(FileUid),CONSTRAINT UQ_PatientFile_StorageKey UNIQUE(StorageKey),CONSTRAINT CK_PatientFile_Status CHECK(Status IN(N'Active',N'Archived')),CONSTRAINT CK_PatientFile_Size CHECK(FileSizeBytes>=0),CONSTRAINT FK_PatientFile_Patient FOREIGN KEY(PatientUid) REFERENCES dbo.Patient(PatientUid),CONSTRAINT FK_PatientFile_UploadedBy FOREIGN KEY(UploadedBy) REFERENCES dbo.ApplicationUser(UserId),CONSTRAINT FK_PatientFile_UpdatedBy FOREIGN KEY(UpdatedBy) REFERENCES dbo.ApplicationUser(UserId));
CREATE INDEX IX_PatientFile_PatientUid_UploadedAt ON dbo.PatientFile(PatientUid,UploadedAt DESC);
CREATE INDEX IX_PatientFile_PatientUid_Status ON dbo.PatientFile(PatientUid,Status);
GO
CREATE OR ALTER PROCEDURE dbo.PatientFile_GetByPatientUid @PatientUid UNIQUEIDENTIFIER AS BEGIN SET NOCOUNT ON;SELECT FileUid,PatientUid,OriginalFileName,StorageKey,ContentType,FileSizeBytes,FileExtension,Sha256Hash,Description,Category,Status,UploadedAt,UploadedBy,UpdatedAt,UpdatedBy,RowVersion FROM dbo.PatientFile WHERE PatientUid=@PatientUid ORDER BY UploadedAt DESC,FileUid DESC;END;
GO
CREATE OR ALTER PROCEDURE dbo.PatientFile_GetByUid @PatientUid UNIQUEIDENTIFIER,@FileUid UNIQUEIDENTIFIER AS BEGIN SET NOCOUNT ON;SELECT FileUid,PatientUid,OriginalFileName,StorageKey,ContentType,FileSizeBytes,FileExtension,Sha256Hash,Description,Category,Status,UploadedAt,UploadedBy,UpdatedAt,UpdatedBy,RowVersion FROM dbo.PatientFile WHERE PatientUid=@PatientUid AND FileUid=@FileUid;END;
GO
CREATE OR ALTER PROCEDURE dbo.PatientFile_Create @PatientUid UNIQUEIDENTIFIER,@OriginalFileName NVARCHAR(255),@StorageKey NVARCHAR(500),@ContentType NVARCHAR(200),@FileSizeBytes BIGINT,@FileExtension NVARCHAR(20)=NULL,@Sha256Hash CHAR(64)=NULL,@Description NVARCHAR(1000)=NULL,@Category NVARCHAR(100)=NULL,@UploadedBy BIGINT AS BEGIN SET NOCOUNT ON;SET XACT_ABORT ON;IF NOT EXISTS(SELECT 1 FROM dbo.Patient WHERE PatientUid=@PatientUid AND IsDeleted=0)THROW 51700,'Patient not found.',1;IF NOT EXISTS(SELECT 1 FROM dbo.ApplicationUser WHERE UserId=@UploadedBy AND IsActive=1)THROW 51701,'Active clinical user not found.',1;DECLARE @FileUid UNIQUEIDENTIFIER=NEWID();INSERT dbo.PatientFile(FileUid,PatientUid,OriginalFileName,StorageKey,ContentType,FileSizeBytes,FileExtension,Sha256Hash,Description,Category,UploadedBy)VALUES(@FileUid,@PatientUid,@OriginalFileName,@StorageKey,@ContentType,@FileSizeBytes,@FileExtension,@Sha256Hash,@Description,@Category,@UploadedBy);DECLARE @PatientId BIGINT=(SELECT PatientId FROM dbo.Patient WHERE PatientUid=@PatientUid);INSERT dbo.AuditLog(UserId,PatientId,ActionName,EntityName,EntityId,NewValue,CreatedAt)VALUES(@UploadedBy,@PatientId,N'Create',N'PatientFile',CONVERT(NVARCHAR(100),@FileUid),N'Status=Active',SYSUTCDATETIME());EXEC dbo.PatientFile_GetByUid @PatientUid,@FileUid;END;
GO
