/* Step 36P-A: tenant-local Provider Management foundation. */
SET XACT_ABORT ON;
GO
IF OBJECT_ID(N'dbo.Provider',N'U') IS NULL OR OBJECT_ID(N'dbo.ApplicationUser',N'U') IS NULL OR OBJECT_ID(N'dbo.AuditLog',N'U') IS NULL
    THROW 51700,'Provider Management prerequisites are missing.',1;
GO
IF EXISTS(SELECT ProviderUid FROM dbo.Provider GROUP BY ProviderUid HAVING COUNT(*)>1)
    THROW 51701,'Duplicate ProviderUid values must be resolved before Provider Management can be installed.',1;
IF EXISTS(SELECT ProviderId FROM dbo.ApplicationUser WHERE ProviderId IS NOT NULL GROUP BY ProviderId HAVING COUNT(*)>1)
    THROW 51702,'A Provider is linked to multiple ApplicationUsers; resolve the links before Provider Management can be installed.',1;
GO
IF COL_LENGTH(N'dbo.Provider',N'UpdatedAt') IS NULL ALTER TABLE dbo.Provider ADD UpdatedAt DATETIME2 NULL;
IF COL_LENGTH(N'dbo.Provider',N'UpdatedBy') IS NULL ALTER TABLE dbo.Provider ADD UpdatedBy BIGINT NULL;
IF COL_LENGTH(N'dbo.Provider',N'RowVersion') IS NULL ALTER TABLE dbo.Provider ADD RowVersion ROWVERSION NOT NULL;
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.Provider') AND name=N'UX_Provider_ProviderUid')
    CREATE UNIQUE INDEX UX_Provider_ProviderUid ON dbo.Provider(ProviderUid);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.ApplicationUser') AND name=N'UX_ApplicationUser_ProviderId')
    CREATE UNIQUE INDEX UX_ApplicationUser_ProviderId ON dbo.ApplicationUser(ProviderId) WHERE ProviderId IS NOT NULL;
GO
CREATE OR ALTER PROCEDURE dbo.Provider_List @Status NVARCHAR(10)=N'Active' AS
BEGIN SET NOCOUNT ON;IF @Status NOT IN(N'Active',N'Inactive',N'All')THROW 51703,'Provider status filter is invalid.',1;
 SELECT p.ProviderUid,p.FirstName,p.LastName,p.DisplayName,p.ProviderType,p.BillingNumber,p.Specialty,p.IsActive,p.CreatedAt,p.CreatedBy,p.UpdatedAt,p.UpdatedBy,u.UserUid LinkedApplicationUserUid,u.DisplayName LinkedApplicationUserDisplayName,u.Email LinkedApplicationUserEmail,p.RowVersion
 FROM dbo.Provider p LEFT JOIN dbo.ApplicationUser u ON u.ProviderId=p.ProviderId WHERE @Status=N'All' OR (@Status=N'Active' AND p.IsActive=1) OR (@Status=N'Inactive' AND p.IsActive=0) ORDER BY p.DisplayName,p.ProviderUid;END;
GO
CREATE OR ALTER PROCEDURE dbo.Provider_Get @ProviderUid UNIQUEIDENTIFIER AS
BEGIN SET NOCOUNT ON;SELECT p.ProviderUid,p.FirstName,p.LastName,p.DisplayName,p.ProviderType,p.BillingNumber,p.Specialty,p.IsActive,p.CreatedAt,p.CreatedBy,p.UpdatedAt,p.UpdatedBy,u.UserUid LinkedApplicationUserUid,u.DisplayName LinkedApplicationUserDisplayName,u.Email LinkedApplicationUserEmail,p.RowVersion FROM dbo.Provider p LEFT JOIN dbo.ApplicationUser u ON u.ProviderId=p.ProviderId WHERE p.ProviderUid=@ProviderUid;END;
GO
CREATE OR ALTER PROCEDURE dbo.Provider_EligibleApplicationUsers_List @ProviderUid UNIQUEIDENTIFIER=NULL AS
BEGIN SET NOCOUNT ON;DECLARE @ProviderId BIGINT=NULL;IF @ProviderUid IS NOT NULL SELECT @ProviderId=ProviderId FROM dbo.Provider WHERE ProviderUid=@ProviderUid;
 SELECT u.UserUid,u.DisplayName,u.Email FROM dbo.ApplicationUser u WHERE u.IsActive=1 AND (u.ProviderId IS NULL OR u.ProviderId=@ProviderId) ORDER BY u.DisplayName,u.UserUid;END;
GO
CREATE OR ALTER PROCEDURE dbo.Provider_Create @FirstName NVARCHAR(100),@LastName NVARCHAR(100),@DisplayName NVARCHAR(200),@ProviderType NVARCHAR(50),@BillingNumber NVARCHAR(50)=NULL,@Specialty NVARCHAR(100)=NULL,@ActorUserId BIGINT AS
BEGIN SET NOCOUNT ON;SET XACT_ABORT ON;IF NOT EXISTS(SELECT 1 FROM dbo.ApplicationUser WHERE UserId=@ActorUserId AND IsActive=1)THROW 51704,'Active actor is required.',1;IF NULLIF(LTRIM(RTRIM(@FirstName)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(@LastName)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(@DisplayName)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(@ProviderType)),N'') IS NULL THROW 51705,'Provider name and type are required.',1;DECLARE @Uid UNIQUEIDENTIFIER=NEWID();BEGIN TRANSACTION;INSERT dbo.Provider(ProviderUid,FirstName,LastName,DisplayName,ProviderType,BillingNumber,Specialty,IsActive,CreatedAt,CreatedBy)VALUES(@Uid,LTRIM(RTRIM(@FirstName)),LTRIM(RTRIM(@LastName)),LTRIM(RTRIM(@DisplayName)),LTRIM(RTRIM(@ProviderType)),NULLIF(LTRIM(RTRIM(@BillingNumber)),N''),NULLIF(LTRIM(RTRIM(@Specialty)),N''),1,SYSUTCDATETIME(),@ActorUserId);INSERT dbo.AuditLog(UserId,PatientId,ActionName,EntityName,EntityId,NewValue,CreatedAt)VALUES(@ActorUserId,NULL,N'ProviderCreated',N'Provider',CONVERT(NVARCHAR(36),@Uid),N'Status=Active',SYSUTCDATETIME());COMMIT;EXEC dbo.Provider_Get @Uid;END;
GO
CREATE OR ALTER PROCEDURE dbo.Provider_Update @ProviderUid UNIQUEIDENTIFIER,@FirstName NVARCHAR(100),@LastName NVARCHAR(100),@DisplayName NVARCHAR(200),@ProviderType NVARCHAR(50),@BillingNumber NVARCHAR(50)=NULL,@Specialty NVARCHAR(100)=NULL,@ExpectedRowVersion BINARY(8),@ActorUserId BIGINT AS
BEGIN SET NOCOUNT ON;SET XACT_ABORT ON;IF NULLIF(LTRIM(RTRIM(@FirstName)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(@LastName)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(@DisplayName)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(@ProviderType)),N'') IS NULL THROW 51705,'Provider name and type are required.',1;BEGIN TRANSACTION;IF NOT EXISTS(SELECT 1 FROM dbo.ApplicationUser WHERE UserId=@ActorUserId AND IsActive=1)THROW 51704,'Active actor is required.',1;DECLARE @Current BINARY(8);SELECT @Current=RowVersion FROM dbo.Provider WITH(UPDLOCK,HOLDLOCK) WHERE ProviderUid=@ProviderUid;IF @Current IS NULL BEGIN ROLLBACK;RETURN;END;IF @Current<>@ExpectedRowVersion THROW 51706,'Provider changed before it could be updated.',1;UPDATE dbo.Provider SET FirstName=LTRIM(RTRIM(@FirstName)),LastName=LTRIM(RTRIM(@LastName)),DisplayName=LTRIM(RTRIM(@DisplayName)),ProviderType=LTRIM(RTRIM(@ProviderType)),BillingNumber=NULLIF(LTRIM(RTRIM(@BillingNumber)),N''),Specialty=NULLIF(LTRIM(RTRIM(@Specialty)),N''),UpdatedAt=SYSUTCDATETIME(),UpdatedBy=@ActorUserId WHERE ProviderUid=@ProviderUid AND RowVersion=@ExpectedRowVersion;INSERT dbo.AuditLog(UserId,PatientId,ActionName,EntityName,EntityId,NewValue,CreatedAt)VALUES(@ActorUserId,NULL,N'ProviderUpdated',N'Provider',CONVERT(NVARCHAR(36),@ProviderUid),N'Provider administrative fields updated',SYSUTCDATETIME());COMMIT;EXEC dbo.Provider_Get @ProviderUid;END;
GO
CREATE OR ALTER PROCEDURE dbo.Provider_SetActive @ProviderUid UNIQUEIDENTIFIER,@IsActive BIT,@ExpectedRowVersion BINARY(8),@ActorUserId BIGINT AS
BEGIN SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRANSACTION;IF NOT EXISTS(SELECT 1 FROM dbo.ApplicationUser WHERE UserId=@ActorUserId AND IsActive=1)THROW 51704,'Active actor is required.',1;DECLARE @Current BINARY(8),@Old BIT;SELECT @Current=RowVersion,@Old=IsActive FROM dbo.Provider WITH(UPDLOCK,HOLDLOCK) WHERE ProviderUid=@ProviderUid;IF @Current IS NULL BEGIN ROLLBACK;RETURN;END;IF @Current<>@ExpectedRowVersion THROW 51706,'Provider changed before its status could be updated.',1;IF @Old=@IsActive THROW 51707,'Provider is already in the requested status.',1;UPDATE dbo.Provider SET IsActive=@IsActive,UpdatedAt=SYSUTCDATETIME(),UpdatedBy=@ActorUserId WHERE ProviderUid=@ProviderUid AND RowVersion=@ExpectedRowVersion;INSERT dbo.AuditLog(UserId,PatientId,ActionName,EntityName,EntityId,NewValue,CreatedAt)VALUES(@ActorUserId,NULL,CASE WHEN @IsActive=1 THEN N'ProviderReactivated' ELSE N'ProviderDeactivated' END,N'Provider',CONVERT(NVARCHAR(36),@ProviderUid),CASE WHEN @IsActive=1 THEN N'Status=Active' ELSE N'Status=Inactive' END,SYSUTCDATETIME());COMMIT;EXEC dbo.Provider_Get @ProviderUid;END;
GO
CREATE OR ALTER PROCEDURE dbo.Provider_LinkApplicationUser @ProviderUid UNIQUEIDENTIFIER,@ApplicationUserUid UNIQUEIDENTIFIER,@ExpectedRowVersion BINARY(8),@ActorUserId BIGINT AS
BEGIN SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRANSACTION;IF NOT EXISTS(SELECT 1 FROM dbo.ApplicationUser WHERE UserId=@ActorUserId AND IsActive=1)THROW 51704,'Active actor is required.',1;DECLARE @ProviderId BIGINT,@Current BINARY(8),@Active BIT,@UserId BIGINT;SELECT @ProviderId=ProviderId,@Current=RowVersion,@Active=IsActive FROM dbo.Provider WITH(UPDLOCK,HOLDLOCK) WHERE ProviderUid=@ProviderUid;IF @ProviderId IS NULL BEGIN ROLLBACK;RETURN;END;IF @Current<>@ExpectedRowVersion THROW 51706,'Provider changed before it could be linked.',1;IF @Active=0 THROW 51708,'Only an active Provider can be linked.',1;SELECT @UserId=UserId FROM dbo.ApplicationUser WITH(UPDLOCK,HOLDLOCK) WHERE UserUid=@ApplicationUserUid AND IsActive=1 AND ProviderId IS NULL;IF @UserId IS NULL THROW 51709,'Eligible active ApplicationUser was not found.',1;IF EXISTS(SELECT 1 FROM dbo.ApplicationUser WHERE ProviderId=@ProviderId)THROW 51710,'Provider is already linked.',1;UPDATE dbo.ApplicationUser SET ProviderId=@ProviderId WHERE UserId=@UserId AND ProviderId IS NULL;UPDATE dbo.Provider SET UpdatedAt=SYSUTCDATETIME(),UpdatedBy=@ActorUserId WHERE ProviderId=@ProviderId AND RowVersion=@ExpectedRowVersion;INSERT dbo.AuditLog(UserId,PatientId,ActionName,EntityName,EntityId,NewValue,CreatedAt)VALUES(@ActorUserId,NULL,N'ProviderUserLinked',N'Provider',CONVERT(NVARCHAR(36),@ProviderUid),CONCAT(N'ApplicationUserUid=',CONVERT(NVARCHAR(36),@ApplicationUserUid)),SYSUTCDATETIME());COMMIT;EXEC dbo.Provider_Get @ProviderUid;END;
GO
CREATE OR ALTER PROCEDURE dbo.Provider_UnlinkApplicationUser @ProviderUid UNIQUEIDENTIFIER,@ApplicationUserUid UNIQUEIDENTIFIER,@ExpectedRowVersion BINARY(8),@ActorUserId BIGINT AS
BEGIN SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRANSACTION;IF NOT EXISTS(SELECT 1 FROM dbo.ApplicationUser WHERE UserId=@ActorUserId AND IsActive=1)THROW 51704,'Active actor is required.',1;DECLARE @ProviderId BIGINT,@Current BINARY(8),@UserId BIGINT;SELECT @ProviderId=ProviderId,@Current=RowVersion FROM dbo.Provider WITH(UPDLOCK,HOLDLOCK) WHERE ProviderUid=@ProviderUid;IF @ProviderId IS NULL BEGIN ROLLBACK;RETURN;END;IF @Current<>@ExpectedRowVersion THROW 51706,'Provider changed before it could be unlinked.',1;SELECT @UserId=UserId FROM dbo.ApplicationUser WITH(UPDLOCK,HOLDLOCK) WHERE UserUid=@ApplicationUserUid AND ProviderId=@ProviderId;IF @UserId IS NULL THROW 51711,'Provider link was not found.',1;UPDATE dbo.ApplicationUser SET ProviderId=NULL WHERE UserId=@UserId AND ProviderId=@ProviderId;UPDATE dbo.Provider SET UpdatedAt=SYSUTCDATETIME(),UpdatedBy=@ActorUserId WHERE ProviderId=@ProviderId AND RowVersion=@ExpectedRowVersion;INSERT dbo.AuditLog(UserId,PatientId,ActionName,EntityName,EntityId,NewValue,CreatedAt)VALUES(@ActorUserId,NULL,N'ProviderUserUnlinked',N'Provider',CONVERT(NVARCHAR(36),@ProviderUid),CONCAT(N'ApplicationUserUid=',CONVERT(NVARCHAR(36),@ApplicationUserUid)),SYSUTCDATETIME());COMMIT;EXEC dbo.Provider_Get @ProviderUid;END;
GO
