using System.Data;
using Microsoft.Data.SqlClient;
using MicroEMR.Application.PatientPrescriptions;
using MicroEMR.Infrastructure.Tenancy;

namespace MicroEMR.Infrastructure.PatientPrescriptions;

public sealed class PatientPrescriptionRepository(ITenantSqlConnectionFactory connections):IPatientPrescriptionRepository
{
 public async Task<IReadOnlyList<PatientPrescriptionResponse>> ListAsync(Guid patientUid,CancellationToken token=default){await using var c=await connections.OpenConnectionAsync(token);await using var q=Cmd(c,"dbo.PatientPrescription_GetByPatientUid");Uid(q,"@PatientUid",patientUid);await using var r=await q.ExecuteReaderAsync(token);var x=new List<PatientPrescriptionResponse>();while(await r.ReadAsync(token))x.Add(Map(r));return x;}
 public async Task<PatientPrescriptionResponse?> GetAsync(Guid p,Guid u,CancellationToken t=default)=>await One("dbo.PatientPrescription_GetByUid",p,u,null,null,t);
 public Task<PatientPrescriptionResponse> CreateAsync(Guid p,CreatePrescriptionDraftRequest r,long a,CancellationToken t=default)=>Mutate("dbo.PatientPrescription_CreateDraft",p,null,r,a,null,r.SupersedesPrescriptionUid,t);
 public async Task<PatientPrescriptionResponse?> UpdateAsync(Guid p,Guid u,PrescriptionDraftRequest r,long a,CancellationToken t=default)=>await Mutate("dbo.PatientPrescription_UpdateDraft",p,u,r,a,r.RowVersion,null,t);
 public async Task<PatientPrescriptionResponse?> FinalizeAsync(Guid p,Guid u,string v,long a,CancellationToken t=default)=>await One("dbo.PatientPrescription_Finalize",p,u,v,(q)=>Actor(q,a),t);
 public async Task<PatientPrescriptionResponse?> CancelAsync(Guid p,Guid u,string v,string? reason,long a,CancellationToken t=default)=>await One("dbo.PatientPrescription_Cancel",p,u,v,q=>{Actor(q,a);Str(q,"@Reason",reason,500);},t);
 public async Task<PrescriptionArtifact?> GetArtifactAsync(Guid p,Guid u,CancellationToken t=default){await using var c=await connections.OpenConnectionAsync(t);await using var q=Cmd(c,"dbo.PatientPrescription_GetArtifact");Uid(q,"@PatientUid",p);Uid(q,"@PrescriptionUid",u);await using var r=await q.ExecuteReaderAsync(t);return await r.ReadAsync(t)?new(r.GetGuid(0),r.GetString(2)):null;}
 private async Task<PatientPrescriptionResponse> Mutate(string sp,Guid p,Guid? u,PrescriptionDraftRequest r,long a,string? version,Guid? supersedes,CancellationToken t){await using var c=await connections.OpenConnectionAsync(t);await using var q=Cmd(c,sp);Uid(q,"@PatientUid",p);if(u.HasValue)Uid(q,"@PrescriptionUid",u.Value);Str(q,"@ProductName",r.ProductName,200,false);Str(q,"@ProductIdentifierNamespace",r.ProductIdentifierNamespace,100);Str(q,"@ProductIdentifierValue",r.ProductIdentifierValue,100);Str(q,"@ProductDisplayText",r.ProductDisplayText,300,false);Dec(q,"@StrengthValue",r.StrengthValue,18,6);Str(q,"@StrengthUnit",r.StrengthUnit,50);Dec(q,"@DoseAmount",r.DoseAmount,18,6);Str(q,"@DoseUnit",r.DoseUnit,50);Str(q,"@Route",r.Route,100,false);Str(q,"@FrequencyCode",r.FrequencyCode,40,false);Str(q,"@FrequencyDisplay",PrescriptionFrequencies.Values[r.FrequencyCode],100,false);q.Parameters.Add("@Prn",SqlDbType.Bit).Value=r.Prn;Str(q,"@Directions",r.Directions,1000,false);Dec(q,"@Quantity",r.Quantity,18,3);Str(q,"@QuantityUnit",r.QuantityUnit,50,false);q.Parameters.Add("@AuthorizedRepeats",SqlDbType.Int).Value=r.AuthorizedRepeats;Str(q,"@Indication",r.Indication,500);q.Parameters.Add("@PrescribedDate",SqlDbType.Date).Value=r.PrescribedDate.ToDateTime(TimeOnly.MinValue);q.Parameters.Add("@StartDate",SqlDbType.Date).Value=r.StartDate?.ToDateTime(TimeOnly.MinValue)??(object)DBNull.Value;Actor(q,a);if(supersedes.HasValue)Uid(q,"@SupersedesPrescriptionUid",supersedes.Value);else if(sp.EndsWith("CreateDraft",StringComparison.Ordinal))q.Parameters.Add("@SupersedesPrescriptionUid",SqlDbType.UniqueIdentifier).Value=DBNull.Value;if(version is not null)Version(q,version);try{await using var rd=await q.ExecuteReaderAsync(t);if(!await rd.ReadAsync(t))throw new InvalidOperationException($"{sp} returned no record.");return Map(rd);}catch(SqlException e)when(e.Number is 51504 or 51505){throw new PatientPrescriptionConcurrencyException(e.Message,e);}}
 private async Task<PatientPrescriptionResponse?> One(string sp,Guid p,Guid u,string? version,Action<SqlCommand>? extra,CancellationToken t){await using var c=await connections.OpenConnectionAsync(t);await using var q=Cmd(c,sp);Uid(q,"@PatientUid",p);Uid(q,"@PrescriptionUid",u);if(version is not null)Version(q,version);extra?.Invoke(q);try{await using var r=await q.ExecuteReaderAsync(t);return await r.ReadAsync(t)?Map(r):null;}catch(SqlException e)when(e.Number is 51504 or 51505){throw new PatientPrescriptionConcurrencyException(e.Message,e);}}
 private static SqlCommand Cmd(SqlConnection c,string sp)=>new(sp,c){CommandType=CommandType.StoredProcedure};private static void Uid(SqlCommand q,string n,Guid v)=>q.Parameters.Add(n,SqlDbType.UniqueIdentifier).Value=v;private static void Actor(SqlCommand q,long a)=>q.Parameters.Add("@ActorUserId",SqlDbType.BigInt).Value=a;private static void Version(SqlCommand q,string v)=>q.Parameters.Add("@RowVersion",SqlDbType.Timestamp).Value=Convert.FromBase64String(v);private static void Str(SqlCommand q,string n,string? v,int s,bool nullable=true)=>q.Parameters.Add(n,SqlDbType.NVarChar,s).Value=string.IsNullOrWhiteSpace(v)&&nullable?DBNull.Value:v!.Trim();private static void Dec(SqlCommand q,string n,decimal? v,byte p,byte s){var x=q.Parameters.Add(n,SqlDbType.Decimal);x.Precision=p;x.Scale=s;x.Value=v??(object)DBNull.Value;}
 private static PatientPrescriptionResponse Map(SqlDataReader r){T? N<T>(string n)where T:struct{var i=r.GetOrdinal(n);return r.IsDBNull(i)?null:r.GetFieldValue<T>(i);}string? S(string n){var i=r.GetOrdinal(n);return r.IsDBNull(i)?null:r.GetString(i);}return new(){PrescriptionUid=r.GetGuid(r.GetOrdinal("PrescriptionUid")),PatientUid=r.GetGuid(r.GetOrdinal("PatientUid")),Status=S("Status")!,ProductName=S("ProductName")!,ProductIdentifierNamespace=S("ProductIdentifierNamespace"),ProductIdentifierValue=S("ProductIdentifierValue"),ProductDisplayText=S("ProductDisplayText")!,StrengthValue=N<decimal>("StrengthValue"),StrengthUnit=S("StrengthUnit"),DoseAmount=N<decimal>("DoseAmount"),DoseUnit=S("DoseUnit"),Route=S("Route")!,FrequencyCode=S("FrequencyCode")!,FrequencyDisplay=S("FrequencyDisplay")!,Prn=r.GetBoolean(r.GetOrdinal("Prn")),Directions=S("Directions")!,Quantity=r.GetDecimal(r.GetOrdinal("Quantity")),QuantityUnit=S("QuantityUnit")!,AuthorizedRepeats=r.GetInt32(r.GetOrdinal("AuthorizedRepeats")),Indication=S("Indication"),PrescribedDate=DateOnly.FromDateTime(r.GetDateTime(r.GetOrdinal("PrescribedDate"))),StartDate=N<DateTime>("StartDate") is { } sd?DateOnly.FromDateTime(sd):null,CreatedBy=r.GetInt64(r.GetOrdinal("CreatedBy")),CreatedAtUtc=r.GetDateTime(r.GetOrdinal("CreatedAtUtc")),UpdatedBy=N<long>("UpdatedBy"),UpdatedAtUtc=N<DateTime>("UpdatedAtUtc"),PrescriberUserId=r.GetInt64(r.GetOrdinal("PrescriberUserId")),PrescriberProviderUid=r.GetGuid(r.GetOrdinal("PrescriberProviderUid")),PrescriberDisplayNameSnapshot=S("PrescriberDisplayNameSnapshot"),PrescriberCredentialSnapshot=S("PrescriberCredentialSnapshot"),ProductDisplaySnapshot=S("ProductDisplaySnapshot"),FinalizedBy=N<long>("FinalizedBy"),FinalizedAtUtc=N<DateTime>("FinalizedAtUtc"),CancelledBy=N<long>("CancelledBy"),CancelledAtUtc=N<DateTime>("CancelledAtUtc"),CancellationReason=S("CancellationReason"),SupersedesPrescriptionUid=N<Guid>("SupersedesPrescriptionUid"),SupersededByPrescriptionUid=N<Guid>("SupersededByPrescriptionUid"),ArtifactUid=N<Guid>("ArtifactUid"),RowVersion=Convert.ToBase64String((byte[])r["RowVersion"])};}
}
