using MicroEMR.Application.AccessProfiles;using MicroEMR.Application.Tenancy;using MicroEMR.Application.TenantUserAdministration;using Xunit;
namespace MicroEMR.Api.Tests;
public sealed class AccessProfileFoundationTests
{
 [Fact]public void CatalogKeysAreKnownUniqueAndDeterministicallyGrouped(){Assert.Equal(PermissionCatalog.All.Count,PermissionCatalog.All.Select(x=>x.Key).Distinct(StringComparer.Ordinal).Count());Assert.All(PermissionCatalog.All,x=>Assert.True(PermissionCatalog.IsKnown(x.Key)));Assert.Equal(PermissionCatalog.All.Select(x=>x.Group).Distinct().Order(),PermissionCatalog.All.Select(x=>x.Group).Distinct().Order());}
 [Fact]public async Task UnknownPermissionIsRejectedBeforePersistence(){var repo=new Repo("Active",["Patients.View"]);var service=Service(repo);await Assert.ThrowsAsync<ArgumentException>(()=>service.UpdatePermissionsAsync(Guid.NewGuid(),["Unknown.Power"],"AAAAAAAAAAE="));Assert.Equal(0,repo.UpdateCalls);}
 [Fact]public async Task ActiveMembershipReceivesProfilePermissions(){var service=Service(new Repo("Active",["Patients.View","Encounters.View"]));Assert.True(await service.HasPermissionAsync("user","Patients.View"));Assert.Equal(2,(await service.GetEffectivePermissionsAsync("user")).Count);}
 [Fact]public async Task InactiveMembershipHasNoEffectivePermissionsAndReactivationRestoresThem(){var repo=new Repo("Inactive",["Users.ManageAccess"]);var service=Service(repo);Assert.Empty(await service.GetEffectivePermissionsAsync("user"));repo.Status="Active";Assert.Contains("Users.ManageAccess",await service.GetEffectivePermissionsAsync("user"));}
 [Fact]public void MigrationIsTenantScopedBackfillsRolesAuditsAndUsesConcurrency(){var sql=File.ReadAllText(Path.Combine(Root(),"db","platform","010_access_profiles.sql"));Assert.Contains("TenantUid",sql);Assert.Contains("system-migration-010",sql);Assert.Contains("ClinicAdministrator",sql);Assert.Contains("@ExpectedRowVersion",sql);Assert.Contains("AccessProfilePermissionsChanged",sql);Assert.Contains("UserAccessProfileChanged",sql);Assert.Contains("AND p.TenantUid=m.TenantUid",sql);}
 [Fact]public void DefaultProfilesAreSeeded(){var sql=File.ReadAllText(Path.Combine(Root(),"db","platform","010_access_profiles.sql"));foreach(var name in new[]{"Clinic Administrator","Physician","Nurse","Medical Assistant","Reception / Scheduling","Read Only"})Assert.Contains($"N'{name}'",sql);}
 [Fact]public void DefaultSeedAvoidsAlwaysEncryptedTopLevelLiteralVariables(){var sql=File.ReadAllText(Path.Combine(Root(),"db","platform","010_access_profiles.sql"));Assert.DoesNotContain("DECLARE @All",sql);Assert.Contains("CREATE OR ALTER PROCEDURE dbo.AccessProfile_SeedDefaults",sql);Assert.Contains("EXEC dbo.AccessProfile_SeedDefaults @Tenant",sql);}
 [Fact]public void AssignmentPrimaryKeyCorrectionIsSequentialAndIdempotent(){var sql=File.ReadAllText(Path.Combine(Root(),"db","platform","011_access_profile_assignment_nonclustered_key.sql"));Assert.Contains("index_definition.type = 1",sql);Assert.Contains("DROP CONSTRAINT PK_UserTenantAccessProfile",sql);Assert.Contains("PRIMARY KEY NONCLUSTERED (UserId, TenantUid)",sql);Assert.Contains("index_definition.type = 2",sql);}
 private static AccessProfileService Service(Repo r)=>new(new TenantContext(Guid.NewGuid(),"t","Tenant"),r,new Subject());
 private static string Root()=>Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"..","..","..","..",".."));
 private sealed class Subject:IAuthenticatedSubjectAccessor{public string GetRequiredSubject()=>"admin";}
 private sealed class Repo(string status,IReadOnlyCollection<string> keys):IAccessProfileRepository
 {public string Status{get;set;}=status;public int UpdateCalls{get;private set;}public Task<(string MembershipStatus,IReadOnlyCollection<string> PermissionKeys)>GetEffectiveAsync(Guid t,string u,CancellationToken c=default)=>Task.FromResult((Status,keys));public Task UpdatePermissionsAsync(Guid t,Guid p,IReadOnlyCollection<string> k,string v,string a,CancellationToken c=default){UpdateCalls++;return Task.CompletedTask;}public Task<IReadOnlyList<AccessProfileSummary>>ListAsync(Guid t,CancellationToken c=default)=>Task.FromResult<IReadOnlyList<AccessProfileSummary>>([]);public Task<AccessProfileDetails?>GetAsync(Guid t,Guid p,CancellationToken c=default)=>Task.FromResult<AccessProfileDetails?>(null);public Task<IReadOnlyDictionary<string,UserAccessProfile>>GetAssignmentsAsync(Guid t,IReadOnlyCollection<string> u,CancellationToken c=default)=>Task.FromResult<IReadOnlyDictionary<string,UserAccessProfile>>(new Dictionary<string,UserAccessProfile>());public Task AssignAsync(Guid t,string u,Guid p,string v,string a,CancellationToken c=default)=>Task.CompletedTask;}
}
