using System.Reflection;using System.Text.Json;using MicroEMR.Api.Authorization;using MicroEMR.Api.Controllers;using MicroEMR.Application.AccessProfiles;using MicroEMR.Application.PatientResults;using Xunit;
namespace MicroEMR.Api.Tests;
public sealed class ResultsProvenanceCorrectionFoundationTests
{
 private static readonly string Sql=File.ReadAllText(Path.Combine(Root(),"db","tenant-clinical","migrations","0054-results-provenance-correction-foundation.sql"));
 [Fact]public void Migration0054RemainsUniqueAndImmutable(){using var d=JsonDocument.Parse(File.ReadAllText(Path.Combine(Root(),"db","tenant-clinical","manifest.json")));var x=d.RootElement.EnumerateArray().ToArray();Assert.Equal("0054-results-provenance-correction-foundation",x[^2].GetProperty("migrationId").GetString());Assert.Equal("0055-verified-negative-allergy-assertion",x[^1].GetProperty("migrationId").GetString());Assert.Single(x,e=>e.GetProperty("migrationId").GetString()=="0054-results-provenance-correction-foundation");}
 [Fact]public void LegacyBackfillAndControlledStatesAreDeterministic(){Assert.Contains("DEFAULT N'Current'",Sql);Assert.Contains("DEFAULT N'Manual'",Sql);Assert.Contains("DEFAULT N'Unknown'",Sql);Assert.Contains("LifecycleStatus IN(N'Current',N'Superseded',N'EnteredInError')",Sql);Assert.Contains("SourceType IN(N'Manual',N'External')",Sql);Assert.Contains("Abnormality IN(N'Unknown',N'Normal',N'Abnormal')",Sql);Assert.DoesNotContain("Critical",Sql);}
 [Fact]public void ProvenanceValidationIsBoundedAndIdentifierNotGloballyUnique(){Assert.Contains("External Result ID requires a source system",Sql);Assert.Contains("External Results require received time and source identity",Sql);Assert.Contains("CREATE INDEX IX_PatientResult_ExternalIdentity",Sql);Assert.DoesNotContain("CREATE UNIQUE INDEX IX_PatientResult_ExternalIdentity",Sql);Assert.DoesNotContain("Accession",Sql);Assert.DoesNotContain("OLIS",Sql,StringComparison.OrdinalIgnoreCase);}
 [Fact]public void UpdateIsCurrentNewConcurrentAndAtomic(){var p=Procedure("dbo.PatientResult_Update");Assert.Contains("@ExpectedRowVersion BINARY(8)",p);Assert.Contains("@Status<>N'New' OR @Lifecycle<>N'Current'",p);Assert.Contains("RowVersion=@ExpectedRowVersion",p);Assert.Contains("N'ResultUpdated'",p);Assert.Contains("BEGIN TRANSACTION",p);}
 [Fact]public void CorrectionPreservesReviewedPredecessorAndPreventsBranches(){var p=Procedure("dbo.PatientResult_Correct");Assert.Contains("@Status<>N'Reviewed' OR @Lifecycle<>N'Current'",p);Assert.Contains("PreviousResultUid",p);Assert.Contains("LifecycleStatus=N'Superseded'",p);Assert.Contains("N'ResultCorrected'",p);Assert.Contains("UX_PatientResult_PreviousResultUid",Sql);Assert.DoesNotContain("ReviewedBy",p);Assert.DoesNotContain("DELETE FROM",p,StringComparison.OrdinalIgnoreCase);}
 [Fact]public void EnteredInErrorIsCurrentConcurrentReasonedAndNeverDeletes(){var p=Procedure("dbo.PatientResult_MarkEnteredInError");Assert.Contains("reason is required",p,StringComparison.OrdinalIgnoreCase);Assert.Contains("@Lifecycle<>N'Current'",p);Assert.Contains("RowVersion=@ExpectedRowVersion",p);Assert.Contains("N'ResultEnteredInError'",p);Assert.DoesNotContain("DELETE FROM",Sql,StringComparison.OrdinalIgnoreCase);}
 [Fact]public void ReviewSemanticsRemainCurrentIdempotentAndAtomic(){var p=Procedure("dbo.PatientResult_MarkReviewed");Assert.Contains("@CurrentStatus=N'New'",p);Assert.Contains("@ReviewWasApplied BIT=0",p);Assert.Contains("N'ResultReviewed'",p);Assert.Contains("@Lifecycle<>N'Current'",p);Assert.Equal(1,p.Split("N'ResultReviewed'",StringSplitOptions.None).Length-1);}
 [Fact]public void ApiPermissionsActorsAndPatientScopeAreAuthoritative(){var t=typeof(PatientResultsController);foreach(var n in new[]{nameof(PatientResultsController.Correct),nameof(PatientResultsController.EnteredInError)})Assert.Contains(t.GetMethod(n)!.GetCustomAttributes<RequirePermissionAttribute>(),a=>a.Policy?.Contains(PermissionKeys.ResultsReview)==true);Assert.Null(typeof(CorrectPatientResultRequest).GetProperty("CorrectedBy"));Assert.Null(typeof(MarkPatientResultEnteredInErrorRequest).GetProperty("Actor"));Assert.Contains("@PatientUid UNIQUEIDENTIFIER,@PatientResultUid",Sql);}
 [Fact]public void CurrentOnlyQueriesAndHistoryPreserveWorkflow(){Assert.Contains("r.LifecycleStatus=N'Current'",Procedure("dbo.PatientResult_GetUnreviewed"));Assert.Contains("r.LifecycleStatus=N'Current'",Procedure("dbo.PatientResult_GetUnreviewedCount"));Assert.Contains("CREATE OR ALTER PROCEDURE dbo.PatientResult_GetHistory",Sql);Assert.Contains("PreviousResultUid=l.PatientResultUid",Sql);}
 [Fact]public void NoAutomaticInterpretationCdsOrCdmWasAdded(){Assert.DoesNotContain("ReferenceRange",Procedure("dbo.PatientResult_ValidateFoundation"));Assert.DoesNotContain("CdsAlert",Sql);Assert.DoesNotContain("ChronicDisease",Sql);Assert.DoesNotContain("PatientTask",Sql);}
 private static string Procedure(string name){var s=Sql.IndexOf("CREATE OR ALTER PROCEDURE "+name,StringComparison.Ordinal);var e=Sql.IndexOf("\nGO",s,StringComparison.Ordinal);return Sql[s..e];}
 private static string Root([System.Runtime.CompilerServices.CallerFilePath]string source="")=>Path.GetFullPath(Path.Combine(Path.GetDirectoryName(source)!,"..",".."));
}
