using System.Data;
using Microsoft.Data.SqlClient;
using MicroEMR.Application.Providers;
using MicroEMR.Infrastructure.Tenancy;

namespace MicroEMR.Infrastructure.Providers;

public sealed class ProviderAdministrationRepository(ITenantSqlConnectionFactory connections):IProviderAdministrationRepository
{
    public async Task<IReadOnlyList<ProviderAdministrationItem>>ListAsync(string status,CancellationToken token=default){var list=new List<ProviderAdministrationItem>();await using var c=await connections.OpenConnectionAsync(token);await using var q=Command(c,"dbo.Provider_List");q.Parameters.Add("@Status",SqlDbType.NVarChar,10).Value=status;await using var r=await q.ExecuteReaderAsync(token);while(await r.ReadAsync(token))list.Add(Map(r));return list;}
    public async Task<ProviderAdministrationItem?>GetAsync(Guid uid,CancellationToken token=default){await using var c=await connections.OpenConnectionAsync(token);await using var q=Command(c,"dbo.Provider_Get");Guid(q,"@ProviderUid",uid);await using var r=await q.ExecuteReaderAsync(token);return await r.ReadAsync(token)?Map(r):null;}
    public async Task<ProviderAdministrationItem>CreateAsync(SaveProviderRequest x,long actor,CancellationToken token=default)=>await Mutate("dbo.Provider_Create",null,x,null,actor,null,token)??throw new InvalidOperationException("Provider create returned no record.");
    public Task<ProviderAdministrationItem?>UpdateAsync(Guid uid,SaveProviderRequest x,long actor,CancellationToken token=default)=>Mutate("dbo.Provider_Update",uid,x,x.RowVersion,actor,null,token);
    public Task<ProviderAdministrationItem?>SetActiveAsync(Guid uid,bool active,string version,long actor,CancellationToken token=default)=>Mutate("dbo.Provider_SetActive",uid,null,version,actor,q=>q.Parameters.Add("@IsActive",SqlDbType.Bit).Value=active,token);
    public async Task<IReadOnlyList<EligibleApplicationUser>>EligibleUsersAsync(Guid? uid,CancellationToken token=default){var list=new List<EligibleApplicationUser>();await using var c=await connections.OpenConnectionAsync(token);await using var q=Command(c,"dbo.Provider_EligibleApplicationUsers_List");q.Parameters.Add("@ProviderUid",SqlDbType.UniqueIdentifier).Value=uid.HasValue?uid.Value:DBNull.Value;await using var r=await q.ExecuteReaderAsync(token);while(await r.ReadAsync(token))list.Add(new(r.GetGuid(0),r.GetString(1),NString(r,2)));return list;}
    public Task<ProviderAdministrationItem?>LinkAsync(Guid uid,ProviderLinkRequest x,long actor,CancellationToken token=default)=>Link("dbo.Provider_LinkApplicationUser",uid,x,actor,token);
    public Task<ProviderAdministrationItem?>UnlinkAsync(Guid uid,ProviderLinkRequest x,long actor,CancellationToken token=default)=>Link("dbo.Provider_UnlinkApplicationUser",uid,x,actor,token);
    private async Task<ProviderAdministrationItem?>Link(string name,Guid uid,ProviderLinkRequest x,long actor,CancellationToken token)=>await Mutate(name,uid,null,x.RowVersion,actor,q=>Guid(q,"@ApplicationUserUid",x.ApplicationUserUid),token);
    private async Task<ProviderAdministrationItem?>Mutate(string name,Guid? uid,SaveProviderRequest? x,string? version,long actor,Action<SqlCommand>? extra,CancellationToken token)
    {await using var c=await connections.OpenConnectionAsync(token);await using var q=Command(c,name);if(uid.HasValue)Guid(q,"@ProviderUid",uid.Value);if(x is not null){Text(q,"@FirstName",100,x.FirstName);Text(q,"@LastName",100,x.LastName);Text(q,"@DisplayName",200,x.DisplayName);Text(q,"@ProviderType",50,x.ProviderType);Text(q,"@BillingNumber",50,x.BillingNumber);Text(q,"@Specialty",100,x.Specialty);}if(version is not null)q.Parameters.Add("@ExpectedRowVersion",SqlDbType.Timestamp).Value=Convert.FromBase64String(version);q.Parameters.Add("@ActorUserId",SqlDbType.BigInt).Value=actor;extra?.Invoke(q);try{await using var r=await q.ExecuteReaderAsync(token);return await r.ReadAsync(token)?Map(r):null;}catch(SqlException e)when(e.Number==51706){throw new ProviderConcurrencyException();}catch(SqlException e)when(e.Number is 2601 or 2627 or 51707 or 51708 or 51709 or 51710 or 51711){throw new ProviderConflictException(e.Message);}}
    private static ProviderAdministrationItem Map(SqlDataReader r)=>new(r.GetGuid(r.GetOrdinal("ProviderUid")),r.GetString(r.GetOrdinal("FirstName")),r.GetString(r.GetOrdinal("LastName")),r.GetString(r.GetOrdinal("DisplayName")),r.GetString(r.GetOrdinal("ProviderType")),NString(r,"BillingNumber"),NString(r,"Specialty"),r.GetBoolean(r.GetOrdinal("IsActive")),r.GetDateTime(r.GetOrdinal("CreatedAt")),NLong(r,"CreatedBy"),NDate(r,"UpdatedAt"),NLong(r,"UpdatedBy"),NGuid(r,"LinkedApplicationUserUid"),NString(r,"LinkedApplicationUserDisplayName"),NString(r,"LinkedApplicationUserEmail"),Convert.ToBase64String((byte[])r["RowVersion"]));
    private static SqlCommand Command(SqlConnection c,string n)=>new(n,c){CommandType=CommandType.StoredProcedure};private static void Guid(SqlCommand q,string n,Guid v)=>q.Parameters.Add(n,SqlDbType.UniqueIdentifier).Value=v;private static void Text(SqlCommand q,string n,int size,string? v)=>q.Parameters.Add(n,SqlDbType.NVarChar,size).Value=v is null?DBNull.Value:v;private static string? NString(SqlDataReader r,string n){var i=r.GetOrdinal(n);return r.IsDBNull(i)?null:r.GetString(i);}private static string? NString(SqlDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static long? NLong(SqlDataReader r,string n){var i=r.GetOrdinal(n);return r.IsDBNull(i)?null:r.GetInt64(i);}private static DateTime? NDate(SqlDataReader r,string n){var i=r.GetOrdinal(n);return r.IsDBNull(i)?null:r.GetDateTime(i);}private static Guid? NGuid(SqlDataReader r,string n){var i=r.GetOrdinal(n);return r.IsDBNull(i)?null:r.GetGuid(i);}
}
