IF OBJECT_ID(N'dbo.PatientChartAlert',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.PatientChartAlert(PatientChartAlertId BIGINT IDENTITY(1,1) PRIMARY KEY,PatientChartAlertUid UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_PatientChartAlert_Uid DEFAULT NEWSEQUENTIALID(),PatientUid UNIQUEIDENTIFIER NOT NULL,AlertTitle NVARCHAR(200) NOT NULL,AlertMessage NVARCHAR(1000) NULL,AlertType NVARCHAR(50) NOT NULL CONSTRAINT DF_PatientChartAlert_Type DEFAULT N'General',AlertPriority NVARCHAR(50) NOT NULL CONSTRAINT DF_PatientChartAlert_Priority DEFAULT N'Normal',AlertStatus NVARCHAR(50) NOT NULL CONSTRAINT DF_PatientChartAlert_Status DEFAULT N'Active',ResolvedAt DATETIME2(0) NULL,ResolvedBy BIGINT NULL,ResolutionReason NVARCHAR(500) NULL,CreatedAt DATETIME2(0) NOT NULL CONSTRAINT DF_PatientChartAlert_Created DEFAULT SYSUTCDATETIME(),CreatedBy BIGINT NULL,UpdatedAt DATETIME2(0) NULL,UpdatedBy BIGINT NULL,RowVersion ROWVERSION NOT NULL,CONSTRAINT UQ_PatientChartAlert_Uid UNIQUE(PatientChartAlertUid));
 CREATE INDEX IX_PatientChartAlert_PatientUid_Status ON dbo.PatientChartAlert(PatientUid,AlertStatus);
END;
GO
CREATE OR ALTER PROCEDURE dbo.PatientChartAlert_GetByUid @PatientUid UNIQUEIDENTIFIER,@PatientChartAlertUid UNIQUEIDENTIFIER AS BEGIN SET NOCOUNT ON;SELECT a.*,cu.DisplayName CreatedByDisplayName,uu.DisplayName UpdatedByDisplayName,ru.DisplayName ResolvedByDisplayName FROM dbo.PatientChartAlert a LEFT JOIN dbo.ApplicationUser cu ON cu.UserId=a.CreatedBy LEFT JOIN dbo.ApplicationUser uu ON uu.UserId=a.UpdatedBy LEFT JOIN dbo.ApplicationUser ru ON ru.UserId=a.ResolvedBy WHERE a.PatientUid=@PatientUid AND a.PatientChartAlertUid=@PatientChartAlertUid;END;
GO
CREATE OR ALTER PROCEDURE dbo.PatientChartAlert_GetByPatientUid @PatientUid UNIQUEIDENTIFIER,@StatusFilter NVARCHAR(50)=N'Active' AS BEGIN SET NOCOUNT ON;IF @StatusFilter NOT IN(N'Active',N'Resolved',N'All')SET @StatusFilter=N'Active';SELECT a.*,cu.DisplayName CreatedByDisplayName,uu.DisplayName UpdatedByDisplayName,ru.DisplayName ResolvedByDisplayName FROM dbo.PatientChartAlert a LEFT JOIN dbo.ApplicationUser cu ON cu.UserId=a.CreatedBy LEFT JOIN dbo.ApplicationUser uu ON uu.UserId=a.UpdatedBy LEFT JOIN dbo.ApplicationUser ru ON ru.UserId=a.ResolvedBy WHERE a.PatientUid=@PatientUid AND (@StatusFilter=N'All' OR a.AlertStatus=@StatusFilter) ORDER BY CASE a.AlertPriority WHEN N'Critical' THEN 1 WHEN N'High' THEN 2 WHEN N'Normal' THEN 3 ELSE 4 END,a.CreatedAt DESC;END;
GO
CREATE OR ALTER PROCEDURE dbo.PatientChartAlert_Create @PatientUid UNIQUEIDENTIFIER,@AlertTitle NVARCHAR(200),@AlertMessage NVARCHAR(1000)=NULL,@AlertType NVARCHAR(50)=N'General',@AlertPriority NVARCHAR(50)=N'Normal',@CreatedBy BIGINT=NULL AS BEGIN SET NOCOUNT ON;IF NOT EXISTS(SELECT 1 FROM dbo.Patient WHERE PatientUid=@PatientUid AND IsDeleted=0)THROW 51200,'Patient not found.',1;IF NULLIF(LTRIM(RTRIM(@AlertTitle)),N'') IS NULL THROW 51201,'Alert title is required.',1;IF @AlertType NOT IN(N'General',N'Clinical',N'Administrative',N'Safety',N'Scheduling')SET @AlertType=N'General';IF @AlertPriority NOT IN(N'Low',N'Normal',N'High',N'Critical')SET @AlertPriority=N'Normal';DECLARE @Uid UNIQUEIDENTIFIER=NEWID();INSERT dbo.PatientChartAlert(PatientChartAlertUid,PatientUid,AlertTitle,AlertMessage,AlertType,AlertPriority,CreatedBy)VALUES(@Uid,@PatientUid,LTRIM(RTRIM(@AlertTitle)),NULLIF(LTRIM(RTRIM(@AlertMessage)),N''),@AlertType,@AlertPriority,@CreatedBy);EXEC dbo.PatientChartAlert_GetByUid @PatientUid,@Uid;END;
GO
CREATE OR ALTER PROCEDURE dbo.PatientChartAlert_Update @PatientUid UNIQUEIDENTIFIER,@PatientChartAlertUid UNIQUEIDENTIFIER,@AlertTitle NVARCHAR(200),@AlertMessage NVARCHAR(1000)=NULL,@AlertType NVARCHAR(50)=N'General',@AlertPriority NVARCHAR(50)=N'Normal',@UpdatedBy BIGINT=NULL AS BEGIN SET NOCOUNT ON;IF EXISTS(SELECT 1 FROM dbo.PatientChartAlert WHERE PatientUid=@PatientUid AND PatientChartAlertUid=@PatientChartAlertUid AND AlertStatus=N'Resolved')THROW 51202,'Resolved alerts cannot be edited.',1;IF NULLIF(LTRIM(RTRIM(@AlertTitle)),N'') IS NULL THROW 51201,'Alert title is required.',1;IF @AlertType NOT IN(N'General',N'Clinical',N'Administrative',N'Safety',N'Scheduling')SET @AlertType=N'General';IF @AlertPriority NOT IN(N'Low',N'Normal',N'High',N'Critical')SET @AlertPriority=N'Normal';UPDATE dbo.PatientChartAlert SET AlertTitle=LTRIM(RTRIM(@AlertTitle)),AlertMessage=NULLIF(LTRIM(RTRIM(@AlertMessage)),N''),AlertType=@AlertType,AlertPriority=@AlertPriority,UpdatedAt=SYSUTCDATETIME(),UpdatedBy=@UpdatedBy WHERE PatientUid=@PatientUid AND PatientChartAlertUid=@PatientChartAlertUid;IF @@ROWCOUNT=0 RETURN;EXEC dbo.PatientChartAlert_GetByUid @PatientUid,@PatientChartAlertUid;END;
GO
CREATE OR ALTER PROCEDURE dbo.PatientChartAlert_Resolve @PatientUid UNIQUEIDENTIFIER,@PatientChartAlertUid UNIQUEIDENTIFIER,@ResolutionReason NVARCHAR(500)=NULL,@ResolvedBy BIGINT=NULL AS BEGIN SET NOCOUNT ON;UPDATE dbo.PatientChartAlert SET AlertStatus=N'Resolved',ResolvedAt=COALESCE(ResolvedAt,SYSUTCDATETIME()),ResolvedBy=COALESCE(ResolvedBy,@ResolvedBy),ResolutionReason=COALESCE(ResolutionReason,NULLIF(LTRIM(RTRIM(@ResolutionReason)),N'')),UpdatedAt=SYSUTCDATETIME(),UpdatedBy=@ResolvedBy WHERE PatientUid=@PatientUid AND PatientChartAlertUid=@PatientChartAlertUid;IF @@ROWCOUNT=0 RETURN;EXEC dbo.PatientChartAlert_GetByUid @PatientUid,@PatientChartAlertUid;END;
GO
