using System.Data;
using Microsoft.Data.SqlClient;
using MicroEMR.Application.PatientClinicalHistory;
using MicroEMR.Infrastructure.Tenancy;

namespace MicroEMR.Infrastructure.PatientClinicalHistory;

public sealed class PatientClinicalHistoryRepository(ITenantSqlConnectionFactory connections) : IPatientClinicalHistoryRepository
{
    public async Task<IReadOnlyList<PatientClinicalHistoryResponse>> ListAsync(Guid p,string status,CancellationToken ct=default){var items=new List<PatientClinicalHistoryResponse>();await using var c=await connections.OpenConnectionAsync(ct);await using var q=Cmd(c,"dbo.PatientClinicalHistory_List");q.Parameters.Add("@PatientUid",SqlDbType.UniqueIdentifier).Value=p;q.Parameters.Add("@Status",SqlDbType.NVarChar,20).Value=status;await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))items.Add(Map(r));return items;}
    public async Task<PatientClinicalHistoryResponse> CreateAsync(Guid p,CreatePatientClinicalHistoryRequest x,long a,CancellationToken ct=default)=>await Mutate("dbo.PatientClinicalHistory_Create",p,null,x.HistoryType,x.Description,x.RelevantDate,null,a,ct)??throw new InvalidOperationException("PatientClinicalHistory_Create returned no record.");
    public Task<PatientClinicalHistoryResponse?> UpdateAsync(Guid p,Guid h,UpdatePatientClinicalHistoryRequest x,long a,CancellationToken ct=default)=>Mutate("dbo.PatientClinicalHistory_Update",p,h,x.HistoryType,x.Description,x.RelevantDate,x.RowVersion,a,ct);
    public Task<PatientClinicalHistoryResponse?> ArchiveAsync(Guid p,Guid h,string v,long a,CancellationToken ct=default)=>Mutate("dbo.PatientClinicalHistory_Archive",p,h,null,null,null,v,a,ct);
    private async Task<PatientClinicalHistoryResponse?> Mutate(string procedure,Guid p,Guid?h,string?type,string?description,DateOnly?date,string?version,long actor,CancellationToken ct)
    {try{await using var c=await connections.OpenConnectionAsync(ct);await using var q=Cmd(c,procedure);q.Parameters.Add("@PatientUid",SqlDbType.UniqueIdentifier).Value=p;if(h.HasValue)q.Parameters.Add("@HistoryUid",SqlDbType.UniqueIdentifier).Value=h.Value;if(type is not null)q.Parameters.Add("@HistoryType",SqlDbType.NVarChar,20).Value=type;if(description is not null)q.Parameters.Add("@Description",SqlDbType.NVarChar,1000).Value=description;if(procedure!= "dbo.PatientClinicalHistory_Archive")q.Parameters.Add("@RelevantDate",SqlDbType.Date).Value=date.HasValue?date.Value.ToDateTime(TimeOnly.MinValue):DBNull.Value;if(version is not null)q.Parameters.Add("@ExpectedRowVersion",SqlDbType.Binary,8).Value=Version(version);q.Parameters.Add("@Actor",SqlDbType.BigInt).Value=actor;await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?Map(r):null;}catch(SqlException e)when(e.Number==52105){throw new PatientClinicalHistoryConcurrencyException();}catch(SqlException e)when(e.Number==52106){throw new PatientClinicalHistoryArchivedException();}}
    private static SqlCommand Cmd(SqlConnection c,string n)=>new(n,c){CommandType=CommandType.StoredProcedure};
    private static byte[] Version(string value){try{var v=Convert.FromBase64String(value);return v.Length==8?v:throw new FormatException();}catch(FormatException){throw new PatientClinicalHistoryConcurrencyException();}}
    private static PatientClinicalHistoryResponse Map(SqlDataReader r)=>new(){HistoryUid=r.GetGuid(r.GetOrdinal("HistoryUid")),PatientUid=r.GetGuid(r.GetOrdinal("PatientUid")),HistoryType=r.GetString(r.GetOrdinal("HistoryType")),Description=r.GetString(r.GetOrdinal("Description")),RelevantDate=Day(r,"RelevantDate"),Status=r.GetString(r.GetOrdinal("Status")),CreatedAt=r.GetDateTime(r.GetOrdinal("CreatedAt")),CreatedBy=r.GetInt64(r.GetOrdinal("CreatedBy")),CreatedByDisplayName=Text(r,"CreatedByDisplayName"),UpdatedAt=Time(r,"UpdatedAt"),UpdatedBy=Number(r,"UpdatedBy"),UpdatedByDisplayName=Text(r,"UpdatedByDisplayName"),RowVersion=Convert.ToBase64String((byte[])r["RowVersion"])};
    private static string?Text(SqlDataReader r,string n){var i=r.GetOrdinal(n);return r.IsDBNull(i)?null:r.GetString(i);}private static DateOnly?Day(SqlDataReader r,string n){var i=r.GetOrdinal(n);return r.IsDBNull(i)?null:DateOnly.FromDateTime(r.GetDateTime(i));}private static DateTime?Time(SqlDataReader r,string n){var i=r.GetOrdinal(n);return r.IsDBNull(i)?null:r.GetDateTime(i);}private static long?Number(SqlDataReader r,string n){var i=r.GetOrdinal(n);return r.IsDBNull(i)?null:r.GetInt64(i);}
}
