using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MicroEMR.Application.AccessProfiles;
using MicroEMR.Application.PatientPrescriptions;
using MicroEMR.Web.Authorization;
using MicroEMR.Web.Services.PatientPrescriptions;

namespace MicroEMR.Web.Controllers;
[Authorize,RequireWebPermission(PermissionKeys.PatientsView)]
public sealed class PatientPrescriptionsController(IPatientPrescriptionApiClient api):Controller
{
 [HttpGet,RequireWebPermission(PermissionKeys.PrescriptionsPrescribe)] public IActionResult Create(Guid patientUid)=>View(new CreatePrescriptionDraftRequest{PrescribedDate=DateOnly.FromDateTime(DateTime.Today)});
 [HttpPost,ValidateAntiForgeryToken,RequireWebPermission(PermissionKeys.PrescriptionsPrescribe)] public async Task<IActionResult> Create(Guid patientUid,CreatePrescriptionDraftRequest model,CancellationToken t){if(!ModelState.IsValid)return View(model);try{await api.CreateAsync(patientUid,model,t);TempData["SuccessMessage"]="Prescription draft created.";return RedirectToAction("Details","Patients",new{patientUid,tab="medications"});}catch(HttpRequestException e){ModelState.AddModelError("",e.Message);return View(model);}}
 [HttpGet,RequireWebPermission(PermissionKeys.PrescriptionsPrescribe)] public async Task<IActionResult> Edit(Guid patientUid,Guid prescriptionUid,CancellationToken t){var x=await api.GetAsync(patientUid,prescriptionUid,t);if(x is null)return NotFound();if(x.Status!=PrescriptionStatuses.Draft)return Conflict();return View(new PrescriptionDraftRequest{ProductName=x.ProductName,ProductIdentifierNamespace=x.ProductIdentifierNamespace,ProductIdentifierValue=x.ProductIdentifierValue,ProductDisplayText=x.ProductDisplayText,StrengthValue=x.StrengthValue,StrengthUnit=x.StrengthUnit,DoseAmount=x.DoseAmount,DoseUnit=x.DoseUnit,Route=x.Route,FrequencyCode=x.FrequencyCode,Prn=x.Prn,Directions=x.Directions,Quantity=x.Quantity,QuantityUnit=x.QuantityUnit,AuthorizedRepeats=x.AuthorizedRepeats,Indication=x.Indication,PrescribedDate=x.PrescribedDate,StartDate=x.StartDate,RowVersion=x.RowVersion});}
 [HttpPost,ValidateAntiForgeryToken,RequireWebPermission(PermissionKeys.PrescriptionsPrescribe)] public async Task<IActionResult> Edit(Guid patientUid,Guid prescriptionUid,PrescriptionDraftRequest model,CancellationToken t){if(!ModelState.IsValid)return View(model);try{await api.UpdateAsync(patientUid,prescriptionUid,model,t);return RedirectToAction("Details","Patients",new{patientUid,tab="medications"});}catch(HttpRequestException e){ModelState.AddModelError("",e.Message);return View(model);}}
 [HttpPost,ValidateAntiForgeryToken,RequireWebPermission(PermissionKeys.PrescriptionsPrescribe)] public async Task<IActionResult> Finalize(Guid patientUid,Guid prescriptionUid,string rowVersion,CancellationToken t){await api.ActionAsync(patientUid,prescriptionUid,"finalize",new(){RowVersion=rowVersion},t);return RedirectToAction("Details","Patients",new{patientUid,tab="medications"});}
 [HttpPost,ValidateAntiForgeryToken,RequireWebPermission(PermissionKeys.PrescriptionsPrescribe)] public async Task<IActionResult> Cancel(Guid patientUid,Guid prescriptionUid,string rowVersion,string? reason,CancellationToken t){await api.ActionAsync(patientUid,prescriptionUid,"cancel",new(){RowVersion=rowVersion,Reason=reason},t);return RedirectToAction("Details","Patients",new{patientUid,tab="medications"});}
 [HttpPost,ValidateAntiForgeryToken,RequireWebPermission(PermissionKeys.PrescriptionsPrescribe)] public async Task<IActionResult> Correction(Guid patientUid,Guid prescriptionUid,string rowVersion,CancellationToken t){var x=await api.ActionAsync(patientUid,prescriptionUid,"correction",new(){RowVersion=rowVersion},t);return x is null?NotFound():RedirectToAction(nameof(Edit),new{patientUid,prescriptionUid=x.PrescriptionUid});}
 [HttpGet] public async Task<IActionResult> Artifact(Guid patientUid,Guid prescriptionUid,CancellationToken t){var x=await api.ArtifactAsync(patientUid,prescriptionUid,t);return x is null?NotFound():File(x,"application/pdf",$"prescription-{prescriptionUid:N}.pdf");}
}
