SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
IF OBJECT_ID(N'dbo.AccessProfile',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.AccessProfile(AccessProfileUid UNIQUEIDENTIFIER NOT NULL,TenantUid UNIQUEIDENTIFIER NOT NULL,Name NVARCHAR(100) NOT NULL,Description NVARCHAR(500) NOT NULL,IsBuiltIn BIT NOT NULL,IsActive BIT NOT NULL CONSTRAINT DF_AccessProfile_Active DEFAULT 1,CreatedBy NVARCHAR(450) NOT NULL,CreatedAt DATETIME2(7) NOT NULL CONSTRAINT DF_AccessProfile_Created DEFAULT SYSUTCDATETIME(),UpdatedBy NVARCHAR(450) NULL,UpdatedAt DATETIME2(7) NULL,RowVersion ROWVERSION NOT NULL,CONSTRAINT PK_AccessProfile PRIMARY KEY(AccessProfileUid),CONSTRAINT FK_AccessProfile_Tenant FOREIGN KEY(TenantUid) REFERENCES dbo.Tenant(TenantUid),CONSTRAINT UQ_AccessProfile_TenantName UNIQUE(TenantUid,Name));
 CREATE INDEX IX_AccessProfile_Tenant ON dbo.AccessProfile(TenantUid,IsActive,Name);
END;
GO
IF OBJECT_ID(N'dbo.AccessProfilePermission',N'U') IS NULL
 CREATE TABLE dbo.AccessProfilePermission(AccessProfileUid UNIQUEIDENTIFIER NOT NULL,PermissionKey NVARCHAR(100) NOT NULL,CONSTRAINT PK_AccessProfilePermission PRIMARY KEY(AccessProfileUid,PermissionKey),CONSTRAINT FK_AccessProfilePermission_Profile FOREIGN KEY(AccessProfileUid) REFERENCES dbo.AccessProfile(AccessProfileUid));
GO
IF OBJECT_ID(N'dbo.UserTenantAccessProfile',N'U') IS NULL
 CREATE TABLE dbo.UserTenantAccessProfile(UserId NVARCHAR(450) NOT NULL,TenantUid UNIQUEIDENTIFIER NOT NULL,AccessProfileUid UNIQUEIDENTIFIER NOT NULL,AssignedBy NVARCHAR(450) NOT NULL,AssignedAt DATETIME2(7) NOT NULL CONSTRAINT DF_UserTenantAccessProfile_Assigned DEFAULT SYSUTCDATETIME(),CONSTRAINT PK_UserTenantAccessProfile PRIMARY KEY(UserId,TenantUid),CONSTRAINT FK_UserTenantAccessProfile_Membership FOREIGN KEY(UserId,TenantUid) REFERENCES dbo.UserTenantMembership(UserId,TenantUid),CONSTRAINT FK_UserTenantAccessProfile_Profile FOREIGN KEY(AccessProfileUid) REFERENCES dbo.AccessProfile(AccessProfileUid));
GO
CREATE OR ALTER PROCEDURE dbo.AccessProfile_SeedDefaults @TenantUid UNIQUEIDENTIFIER AS
BEGIN SET NOCOUNT ON;DECLARE @Profiles TABLE(Name NVARCHAR(100),Description NVARCHAR(500),Permissions NVARCHAR(MAX));INSERT @Profiles VALUES
(N'Clinic Administrator',N'Broad clinic administration and clinical access.',N'Patients.View,Patients.Edit,Scheduling.View,Scheduling.Manage,Encounters.View,Encounters.Edit,Encounters.Sign,Documents.View,Documents.Manage,Templates.Use,Templates.Manage,ClinicalData.Manage,Referrals.View,Referrals.Manage,Results.View,Results.Review,Tasks.View,Tasks.Manage,Reports.View,Reports.Export,ClinicSettings.Manage,Users.View,Users.Manage,Users.ManageAccess'),
(N'Physician',N'Clinical care including encounter signing.',N'Patients.View,Patients.Edit,Scheduling.View,Encounters.View,Encounters.Edit,Encounters.Sign,Documents.View,Documents.Manage,Templates.Use,ClinicalData.Manage,Referrals.View,Referrals.Manage,Results.View,Results.Review,Tasks.View,Tasks.Manage,Reports.View'),
(N'Nurse',N'Clinical care without encounter signing.',N'Patients.View,Patients.Edit,Scheduling.View,Encounters.View,Encounters.Edit,Documents.View,Documents.Manage,Templates.Use,ClinicalData.Manage,Referrals.View,Results.View,Results.Review,Tasks.View,Tasks.Manage'),
(N'Medical Assistant',N'Conservative clinical support access.',N'Patients.View,Patients.Edit,Scheduling.View,Encounters.View,Documents.View,Templates.Use,ClinicalData.Manage,Referrals.View,Results.View,Tasks.View,Tasks.Manage'),
(N'Reception / Scheduling',N'Patient demographics and appointment management.',N'Patients.View,Patients.Edit,Scheduling.View,Scheduling.Manage'),
(N'Read Only',N'Broad read-only clinical access.',N'Patients.View,Scheduling.View,Encounters.View,Documents.View,Templates.Use,Referrals.View,Results.View,Tasks.View,Reports.View');DECLARE @Name NVARCHAR(100),@Description NVARCHAR(500),@Keys NVARCHAR(MAX),@Uid UNIQUEIDENTIFIER;DECLARE profiles CURSOR LOCAL FAST_FORWARD FOR SELECT Name,Description,Permissions FROM @Profiles;OPEN profiles;FETCH NEXT FROM profiles INTO @Name,@Description,@Keys;WHILE @@FETCH_STATUS=0 BEGIN SELECT @Uid=AccessProfileUid FROM dbo.AccessProfile WHERE TenantUid=@TenantUid AND Name=@Name;IF @Uid IS NULL BEGIN SET @Uid=NEWID();INSERT dbo.AccessProfile(AccessProfileUid,TenantUid,Name,Description,IsBuiltIn,IsActive,CreatedBy)VALUES(@Uid,@TenantUid,@Name,@Description,1,1,N'system-default');END;INSERT dbo.AccessProfilePermission SELECT @Uid,LTRIM(RTRIM(value)) FROM STRING_SPLIT(@Keys,N',') k WHERE NOT EXISTS(SELECT 1 FROM dbo.AccessProfilePermission p WHERE p.AccessProfileUid=@Uid AND p.PermissionKey=LTRIM(RTRIM(k.value)));SET @Uid=NULL;FETCH NEXT FROM profiles INTO @Name,@Description,@Keys;END;CLOSE profiles;DEALLOCATE profiles;END;
GO
DECLARE @Tenant UNIQUEIDENTIFIER;DECLARE tenants CURSOR LOCAL FAST_FORWARD FOR SELECT TenantUid FROM dbo.Tenant;OPEN tenants;FETCH NEXT FROM tenants INTO @Tenant;WHILE @@FETCH_STATUS=0 BEGIN EXEC dbo.AccessProfile_SeedDefaults @Tenant;FETCH NEXT FROM tenants INTO @Tenant;END;CLOSE tenants;DEALLOCATE tenants;
GO
INSERT dbo.UserTenantAccessProfile(UserId,TenantUid,AccessProfileUid,AssignedBy)
SELECT m.UserId,m.TenantUid,p.AccessProfileUid,N'system-migration-010' FROM dbo.UserTenantMembership m
CROSS APPLY(SELECT TOP(1) CASE r.RoleName WHEN N'ClinicAdministrator' THEN N'Clinic Administrator' WHEN N'Physician' THEN N'Physician' WHEN N'Nurse' THEN N'Nurse' WHEN N'MedicalAssistant' THEN N'Medical Assistant' WHEN N'Scheduler' THEN N'Reception / Scheduling' ELSE N'Read Only' END ProfileName FROM dbo.UserTenantRole r WHERE r.UserId=m.UserId AND r.TenantUid=m.TenantUid ORDER BY CASE r.RoleName WHEN N'ClinicAdministrator' THEN 1 WHEN N'Physician' THEN 2 WHEN N'Nurse' THEN 3 WHEN N'MedicalAssistant' THEN 4 WHEN N'Scheduler' THEN 5 ELSE 6 END) map
JOIN dbo.AccessProfile p ON p.TenantUid=m.TenantUid AND p.Name=map.ProfileName
WHERE NOT EXISTS(SELECT 1 FROM dbo.UserTenantAccessProfile a WHERE a.UserId=m.UserId AND a.TenantUid=m.TenantUid);
GO
CREATE OR ALTER PROCEDURE dbo.AccessProfile_List @TenantUid UNIQUEIDENTIFIER AS BEGIN SET NOCOUNT ON; SELECT p.AccessProfileUid,p.Name,p.Description,p.IsBuiltIn,p.IsActive,COUNT(DISTINCT pp.PermissionKey) PermissionCount,COUNT(DISTINCT a.UserId) AssignedUserCount,p.RowVersion FROM dbo.AccessProfile p LEFT JOIN dbo.AccessProfilePermission pp ON pp.AccessProfileUid=p.AccessProfileUid LEFT JOIN dbo.UserTenantAccessProfile a ON a.AccessProfileUid=p.AccessProfileUid WHERE p.TenantUid=@TenantUid GROUP BY p.AccessProfileUid,p.Name,p.Description,p.IsBuiltIn,p.IsActive,p.RowVersion ORDER BY p.Name; END;
GO
CREATE OR ALTER PROCEDURE dbo.AccessProfile_Get @TenantUid UNIQUEIDENTIFIER,@AccessProfileUid UNIQUEIDENTIFIER AS BEGIN SET NOCOUNT ON; SELECT p.AccessProfileUid,p.Name,p.Description,p.IsBuiltIn,p.IsActive,pp.PermissionKey,(SELECT COUNT(*) FROM dbo.UserTenantAccessProfile a WHERE a.AccessProfileUid=p.AccessProfileUid) AssignedUserCount,p.RowVersion FROM dbo.AccessProfile p LEFT JOIN dbo.AccessProfilePermission pp ON pp.AccessProfileUid=p.AccessProfileUid WHERE p.TenantUid=@TenantUid AND p.AccessProfileUid=@AccessProfileUid ORDER BY pp.PermissionKey; END;
GO
CREATE OR ALTER PROCEDURE dbo.AccessProfile_ReplacePermissions @TenantUid UNIQUEIDENTIFIER,@AccessProfileUid UNIQUEIDENTIFIER,@PermissionKeys NVARCHAR(MAX),@ExpectedRowVersion BINARY(8),@ActorUserId NVARCHAR(450) AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION; DECLARE @Current BINARY(8); SELECT @Current=RowVersion FROM dbo.AccessProfile WITH(UPDLOCK,HOLDLOCK) WHERE TenantUid=@TenantUid AND AccessProfileUid=@AccessProfileUid AND IsActive=1; IF @Current IS NULL THROW 51401,'Profile not found.',1; IF @Current<>@ExpectedRowVersion THROW 51402,'Profile changed.',1; DECLARE @Submitted TABLE(PermissionKey NVARCHAR(100) PRIMARY KEY);INSERT @Submitted SELECT DISTINCT LTRIM(RTRIM(value)) FROM STRING_SPLIT(@PermissionKeys,N',') WHERE LTRIM(RTRIM(value))<>N'';IF NOT EXISTS(SELECT 1 FROM @Submitted) THROW 51403,'At least one permission is required.',1;IF EXISTS(SELECT 1 FROM @Submitted WHERE PermissionKey NOT IN(N'Patients.View',N'Patients.Edit',N'Scheduling.View',N'Scheduling.Manage',N'Encounters.View',N'Encounters.Edit',N'Encounters.Sign',N'Documents.View',N'Documents.Manage',N'Templates.Use',N'Templates.Manage',N'ClinicalData.Manage',N'Referrals.View',N'Referrals.Manage',N'Results.View',N'Results.Review',N'Tasks.View',N'Tasks.Manage',N'Reports.View',N'Reports.Export',N'ClinicSettings.Manage',N'Users.View',N'Users.Manage',N'Users.ManageAccess'))THROW 51403,'Unknown permission.',1; DECLARE @Old NVARCHAR(MAX)=(SELECT PermissionKey FROM dbo.AccessProfilePermission WHERE AccessProfileUid=@AccessProfileUid ORDER BY PermissionKey FOR JSON PATH); DELETE dbo.AccessProfilePermission WHERE AccessProfileUid=@AccessProfileUid; INSERT dbo.AccessProfilePermission SELECT @AccessProfileUid,PermissionKey FROM @Submitted; UPDATE dbo.AccessProfile SET UpdatedBy=@ActorUserId,UpdatedAt=SYSUTCDATETIME() WHERE AccessProfileUid=@AccessProfileUid; DECLARE @New NVARCHAR(MAX)=(SELECT PermissionKey FROM dbo.AccessProfilePermission WHERE AccessProfileUid=@AccessProfileUid ORDER BY PermissionKey FOR JSON PATH); INSERT dbo.PlatformAuditEvent VALUES(NEWID(),@ActorUserId,N'TenantAdmin',N'AccessProfilePermissionsChanged',@TenantUid,NULL,N'Succeeded',SYSUTCDATETIME(),NEWID(),CONCAT(N'{"profileUid":"',@AccessProfileUid,N'","old":',@Old,N',"new":',@New,N'}')); COMMIT; END;
GO
CREATE OR ALTER PROCEDURE dbo.AccessProfile_AssignUser @TenantUid UNIQUEIDENTIFIER,@UserId NVARCHAR(450),@AccessProfileUid UNIQUEIDENTIFIER,@ExpectedMembershipRowVersion BINARY(8),@ActorUserId NVARCHAR(450) AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION; DECLARE @Current BINARY(8),@Old UNIQUEIDENTIFIER; SELECT @Current=RowVersion FROM dbo.UserTenantMembership WITH(UPDLOCK,HOLDLOCK) WHERE TenantUid=@TenantUid AND UserId=@UserId; IF @Current IS NULL THROW 51303,'Membership not found.',1; IF @Current<>@ExpectedMembershipRowVersion THROW 51307,'Membership changed.',1; IF NOT EXISTS(SELECT 1 FROM dbo.AccessProfile WHERE TenantUid=@TenantUid AND AccessProfileUid=@AccessProfileUid AND IsActive=1) THROW 51401,'Active profile not found.',1; SELECT @Old=AccessProfileUid FROM dbo.UserTenantAccessProfile WHERE TenantUid=@TenantUid AND UserId=@UserId; MERGE dbo.UserTenantAccessProfile AS t USING(SELECT @UserId UserId,@TenantUid TenantUid) s ON t.UserId=s.UserId AND t.TenantUid=s.TenantUid WHEN MATCHED THEN UPDATE SET AccessProfileUid=@AccessProfileUid,AssignedBy=@ActorUserId,AssignedAt=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(UserId,TenantUid,AccessProfileUid,AssignedBy) VALUES(@UserId,@TenantUid,@AccessProfileUid,@ActorUserId); UPDATE dbo.UserTenantMembership SET UpdatedAt=SYSUTCDATETIME() WHERE UserId=@UserId AND TenantUid=@TenantUid; INSERT dbo.PlatformAuditEvent VALUES(NEWID(),@ActorUserId,N'TenantAdmin',N'UserAccessProfileChanged',@TenantUid,@UserId,N'Succeeded',SYSUTCDATETIME(),NEWID(),CONCAT(N'{"old":"',COALESCE(CONVERT(NVARCHAR(36),@Old),N''),N'","new":"',@AccessProfileUid,N'"}')); COMMIT; END;
GO
CREATE OR ALTER PROCEDURE dbo.AccessProfile_GetEffective @TenantUid UNIQUEIDENTIFIER,@UserId NVARCHAR(450) AS BEGIN SET NOCOUNT ON; SELECT m.MembershipStatus,pp.PermissionKey FROM dbo.UserTenantMembership m LEFT JOIN dbo.UserTenantAccessProfile a ON a.UserId=m.UserId AND a.TenantUid=m.TenantUid LEFT JOIN dbo.AccessProfile p ON p.AccessProfileUid=a.AccessProfileUid AND p.TenantUid=m.TenantUid AND p.IsActive=1 LEFT JOIN dbo.AccessProfilePermission pp ON pp.AccessProfileUid=p.AccessProfileUid WHERE m.TenantUid=@TenantUid AND m.UserId=@UserId ORDER BY pp.PermissionKey; END;
GO
CREATE OR ALTER PROCEDURE dbo.AccessProfile_GetUserAssignments @TenantUid UNIQUEIDENTIFIER AS BEGIN SET NOCOUNT ON; SELECT m.UserId,a.AccessProfileUid,p.Name,p.IsActive,m.RowVersion FROM dbo.UserTenantMembership m LEFT JOIN dbo.UserTenantAccessProfile a ON a.UserId=m.UserId AND a.TenantUid=m.TenantUid LEFT JOIN dbo.AccessProfile p ON p.AccessProfileUid=a.AccessProfileUid AND p.TenantUid=m.TenantUid WHERE m.TenantUid=@TenantUid; END;
GO
CREATE OR ALTER PROCEDURE dbo.PlatformMembership_CreateWithInitialRole @UserId NVARCHAR(450),@TenantUid UNIQUEIDENTIFIER,@RoleName NVARCHAR(100),@ActorUserId NVARCHAR(450) AS
BEGIN SET NOCOUNT ON;SET XACT_ABORT ON;IF @RoleName NOT IN(N'Physician',N'Nurse',N'MedicalAssistant',N'Scheduler',N'ClinicAdministrator')THROW 51310,'Invalid tenant role.',1;BEGIN TRANSACTION;
IF NOT EXISTS(SELECT 1 FROM dbo.Tenant WITH(UPDLOCK,HOLDLOCK) WHERE TenantUid=@TenantUid AND TenantStatus=N'Active')BEGIN ROLLBACK;THROW 51302,'Tenant is not active.',1;END;
IF EXISTS(SELECT 1 FROM dbo.UserTenantMembership WITH(UPDLOCK,HOLDLOCK) WHERE UserId=@UserId AND TenantUid=@TenantUid)BEGIN ROLLBACK;THROW 51301,'Membership exists.',1;END;
INSERT dbo.UserTenantMembership(UserId,TenantUid,MembershipStatus,IsDefaultTenant,CreatedAt)VALUES(LTRIM(RTRIM(@UserId)),@TenantUid,N'Active',0,SYSUTCDATETIME());INSERT dbo.UserTenantRole(UserId,TenantUid,RoleName)VALUES(LTRIM(RTRIM(@UserId)),@TenantUid,@RoleName);
DECLARE @ProfileName NVARCHAR(100)=CASE @RoleName WHEN N'ClinicAdministrator'THEN N'Clinic Administrator' WHEN N'MedicalAssistant'THEN N'Medical Assistant' WHEN N'Scheduler'THEN N'Reception / Scheduling' ELSE @RoleName END,@ProfileUid UNIQUEIDENTIFIER;SELECT @ProfileUid=AccessProfileUid FROM dbo.AccessProfile WHERE TenantUid=@TenantUid AND Name=@ProfileName AND IsActive=1;IF @ProfileUid IS NULL BEGIN ROLLBACK;THROW 51401,'Default access profile unavailable.',1;END;
INSERT dbo.UserTenantAccessProfile(UserId,TenantUid,AccessProfileUid,AssignedBy)VALUES(LTRIM(RTRIM(@UserId)),@TenantUid,@ProfileUid,@ActorUserId);
INSERT dbo.PlatformAuditEvent VALUES(NEWID(),@ActorUserId,N'TenantAdmin',N'TenantUserCreated',@TenantUid,@UserId,N'Succeeded',SYSUTCDATETIME(),NEWID(),CONCAT(N'{"membershipStatus":"Active","initialRole":"',STRING_ESCAPE(@RoleName,'json'),N'","accessProfile":"',STRING_ESCAPE(@ProfileName,'json'),N'"}'));COMMIT;END;
GO
CREATE OR ALTER PROCEDURE dbo.PlatformTenant_Create @TenantUid UNIQUEIDENTIFIER,@TenantKey NVARCHAR(50),@DisplayName NVARCHAR(200),@DefaultTimeZoneId NVARCHAR(100),@ActorUserId NVARCHAR(450) AS
BEGIN SET NOCOUNT ON;SET XACT_ABORT ON;IF @TenantUid='00000000-0000-0000-0000-000000000000' OR NULLIF(LTRIM(RTRIM(@TenantKey)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(@DisplayName)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(@DefaultTimeZoneId)),N'') IS NULL THROW 51200,'Invalid tenant metadata.',1;BEGIN TRANSACTION;IF EXISTS(SELECT 1 FROM dbo.Tenant WITH(UPDLOCK,HOLDLOCK) WHERE TenantUid=@TenantUid OR TenantKey=LOWER(LTRIM(RTRIM(@TenantKey)))) THROW 51201,'Duplicate tenant.',1;INSERT dbo.Tenant(TenantUid,TenantKey,DisplayName,TenantStatus,DefaultTimeZoneId,CreatedAt)VALUES(@TenantUid,LOWER(LTRIM(RTRIM(@TenantKey))),LTRIM(RTRIM(@DisplayName)),N'Provisioning',LTRIM(RTRIM(@DefaultTimeZoneId)),SYSUTCDATETIME());EXEC dbo.AccessProfile_SeedDefaults @TenantUid;INSERT dbo.PlatformAuditEvent VALUES(NEWID(),NULLIF(LTRIM(RTRIM(@ActorUserId)),N''),N'LocalCli',N'TenantCreated',@TenantUid,NULL,N'Succeeded',SYSUTCDATETIME(),NEWID(),N'{"status":"Provisioning"}');COMMIT;END;
GO
